openapi: 3.0.1
info:
  title: DemoProject
  description: DemoProject
  contact:
    name: Mustafa Babil
    url: https://github.com/mustafababil
  license:
    name: GPLv3
    url: http://foo.bar
  version: 1.0.0
security: []

tags:
  - name: Accounts
    description: All the operations related to Accounts

paths:
  /api/v1/accounts:
    post:
      tags:
        - Accounts
      summary: Create a new account
      description: A new account with initial balance is created
      operationId: createNewAccount
      requestBody:
        $ref: '#/components/requestBodies/NewAccountRequestPayload'
      responses:
        201:
          description: Returns the created account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAccountResponseObject'
        400:
          description: Invalid input supplied
        500:
          description: Server error during creation of account
  /api/v1/accounts/{id}:
    get:
      tags:
        - Accounts
      summary: Get account details
      description: Account details including transactions
      operationId: getAccountDetails
      parameters:
        - $ref: '#/components/parameters/IdPathParameter'
      responses:
        200:
          description: Returns account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailsResponseObject'

components:
  parameters:
    IdPathParameter:
      name: id
      in: path
      description: The unique UUID
      required: true
      schema:
        type: string
        format: uuid
        example: '3115ea04-6c39-481f-9aee-1a4cce028b15'
  requestBodies:
    NewAccountRequestPayload:
      description: Request payload for creating new account
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewAccountRequestObject'
  schemas:
    NewAccountRequestObject:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
          example: '123e4567-e89b-12d3-a456-426655440000'
        initialCredit:
          type: string
          example: "'234.44'"
      required:
        - customerId
        - initialCredit
    NewAccountResponseObject:
      allOf:
        - type: object
          properties:
            accountId:
              type: string
              format: uuid
              example: 'dd22fd5b-ef1e-4480-8074-835d67256766'
          required:
            - accountId
        - $ref: '#/components/schemas/NewAccountRequestObject'
    AccountDetailsResponseObject:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
          example: 'dd22fd5b-ef1e-4480-8074-835d67256766'
        customerId:
          type: string
          format: uuid
          example: '123e4567-e89b-12d3-a456-426655440000'
        balance:
          type: string
          example: "'999.991'"
        name:
          type: string
          example: 'John'
        surname:
          type: string
          example: 'Doe'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionResponseObject'
    TransactionResponseObject:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          example: 'dd22fd5b-ef1e-4480-8074-835d67256766'
        amount:
          type: string
          example: "'123.123'"
        timestamp:
          type: string
          format: 'date-time'
          example: '2020-08-08 19:32:24.50'